# Generated by Django 6.0.6 on 2026-06-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organizer_attivo',
            field=models.BooleanField(default=True),
        ),
    ]
