# Generated by Django 6.0.6 on 2026-06-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stato',
            field=models.IntegerField(default=0),
        ),
    ]
