# Generated by Django 6.0.6 on 2026-06-24 21:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_stato'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPrivato',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('invite_code', models.CharField(max_length=20, unique=True)),
                ('invitation_deadline', models.DateTimeField()),
                ('approval_required', models.BooleanField(default=False)),
                ('secret_location', models.BooleanField(default=False)),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='PublicEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('public_visibility', models.BooleanField(default=True)),
                ('registration_required', models.BooleanField(default=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Numero massimo di partecipanti (lasciare vuoto per illimitato)', null=True)),
            ],
            bases=('events.event',),
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='date_time_end',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 30, 23, 47, 15)),
        ),
        migrations.AddField(
            model_name='event',
            name='date_time_start',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 21, 55, 45, 257190)),
        ),
        migrations.AddField(
            model_name='event',
            name='tipo',
            field=models.CharField(choices=[('PUBLIC', 'Pubblico'), ('PRIVATE', 'Privato')], default='PUBLIC', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'In attesa'), ('PAID', 'Pagato'), ('REFUNDED', 'Rimborsato')], default='PENDING', max_length=20),
        ),
    ]
